export const Routes = {
  bookPage: (number: string | number) => `/talao/${number}`,
  books: '/taloes',
  buyCoffeeMetrics: '/relatorios/compra-cafe',
  clientPage: (uuid: string) => `/cliente/${uuid}`,
  clientPickups: (uuid: string) => `/cliente/${uuid}/cafes-buscar`,
  clients: '/clientes',
  clientSheets: (uuid: string) => `/cliente/${uuid}/folhas`,
  coffeePickups: '/cafes-buscar',
  coffeePrice: '/relatorios/preco-cafe',
  config: '/configuracao',
  createClient: '/clientes/criar',
  createSheet: (bookNumber: string | number) => `/folha/${bookNumber}/criar`,
  fertilizers: '/adubos',
  fertilizersDelivery: '/entrega-adubos',
  login: '/login',
  metricsHub: '/relatorios',
  notFound: '/404',
  sheetDetails: (bookNumber: string | number, sheetNumber: string | number) =>
    `/talao/${bookNumber}/folha/${sheetNumber}`,
  transactionMetrics: '/relatorios/transacoes',
  transfer: '/transferencia',
  updateClient: (uuid: string) => `/clientes/atualizar/${uuid}`,
  updateSheet: (bookNumber: string | number, sheetNumber: string | number) =>
    `/talao/${bookNumber}/folha/${sheetNumber}/atualizar`,
  users: '/usuarios',
} as const
