export const Routes = {
  bookPage: (number: string | number) => `/books/${number}`,
  books: '/books',
  buyCoffeeMetrics: '/metrics/buy-coffee',
  clientPage: (uuid: string) => `/clients/${uuid}`,
  clientPickups: (uuid: string) => `/clients/${uuid}/pickup`,
  clients: '/clients',
  clientSheets: (uuid: string) => `/clients/${uuid}/sheets`,
  coffeePickups: '/coffee-pickups',
  coffeePrice: '/metrics/coffee-price',
  config: '/config',
  createClient: '/clients/create',
  createSheet: (bookNumber: string | number) => `/books/${bookNumber}/create`,
  fertilizers: '/fertilizers',
  fertilizersDelivery: '/fertilizers-delivery',
  login: '/login',
  metricsHub: '/metrics/hub',
  notFound: '/404',
  sheetDetails: (bookNumber: string | number, sheetNumber: string | number) =>
    `/books/${bookNumber}/details/${sheetNumber}`,
  transactionMetrics: '/metrics/transactions',
  transfer: '/transfer',
  updateClient: (uuid: string) => `/clients/update/${uuid}`,
  updateSheet: (bookNumber: string | number, sheetNumber: string | number) =>
    `/books/${bookNumber}/update/${sheetNumber}`,
} as const
