const validationErrors = {
  emailIsRequired: 'Por favor, informe um e-mail',
  emailIsInvalid: 'Por favor, informe um e-mail válido',
  passwordIsRequired: 'Por favor, informe uma senha',
  passwordIsInvalid: 'Por favor, informe uma senha válida',
  nameIsRequired: 'Por favor, informe um nome',
  cpfIsRequired: 'Por favor, informe um CPF',
  cpfIsInvalid: 'Por favor, informe um CPF válido',
  birthDateIsRequired: 'Por favor, informe uma data de nascimento',
  rgIsRequired: 'Por favor, informe um RG',
  fatherNameIsRequired: 'Por favor, informe o nome do pai',
  motherNameIsRequired: 'Por favor, informe o nome da mãe',
  rgEmissionDateIsRequired: 'Por favor, informe a data de emissão do RG',
  producerRegistrationIsRequired: 'Por favor, informe o número de registro do produtor',
  cnpjIsRequired: 'Por favor, informe um CNPJ',
  cnpjIsInvalid: 'Por favor, informe um CNPJ válido',
  stateRegistrationIsRequired: 'Por favor, informe o número de registro estadual',
  valueIsRequired: 'Por favor, informe um valor',
  valueIsInvalid: 'Por favor, informe um valor válido',
  dateIsRequired: 'Por favor, informe uma data',
  descriptionIsRequired: 'Por favor, informe uma descrição',
  fileFormatIsInvalid: 'Formato de arquivo inválido, os formatos válidos são:',
  clientNameIsRequired: 'Por favor, informe o nome do cliente',
  bagsIsRequired: 'Por favor, informe a quantidade de sacas',
  bagsIsInvalid: 'Por favor, informe uma quantidade de sacas válida',
  weightIsRequired: 'Por favor, informe o peso',
  weightIsInvalid: 'Por favor, informe um peso válido',
  addressIsRequired: 'Por favor, informe o endereço',
  bookNumberIsRequired: 'Por favor, informe o número do talão',
  bookNumberIsInvalid: 'Por favor, informe um número de talão válido',
  sheetNumberIsRequired: 'Por favor, informe o número da folha',
  sheetNumberIsInvalid: 'Por favor, informe um número de folha válido',
  courierIsRequired: 'Por favor, informe o nome do motorista',
  clientIsRequired: 'Por favor, informe o nome do cliente',
  coffeeTypeIsRequired: 'Por favor, informe o tipo de café',
  coffeeTypeIsInvalid: 'Por favor, informe um tipo de café válido',
  utilizationIsRequired: 'Por favor, informe a utilização',
  utilizationIsInvalid: 'Por favor, informe uma utilização válida',
  foulnessIsRequired: 'Por favor, informe a impureza',
  foulnessIsInvalid: 'Por favor, informe uma impureza válida',
  bebidaIsRequired: 'Por favor, informe a bebida',
  bebidaIsInvalid: 'Por favor, informe uma bebida válida',
  valuePerBagIsRequired: 'Por favor, informe o valor por saca',
  valuePerBagIsInvalid: 'Por favor, informe um valor por saca válido',
  minValueIsInvalid: (min: number | string) =>
    `Por favor, informe um valor maior ou igual a ${min}`,
  maxValueIsInvalid: (max: number | string) =>
    `Por favor, informe um valor menor ou igual a ${max}`,
  maxLengthIsInvalid: (max: number | string) =>
    `Por favor, informe um valor com no máximo ${max} caracteres`,
  brookIsRequired: 'Por favor, informe o córrego',
  complementIsRequired: 'Por favor, informe o complemento',
  fertilizerIsRequired: 'Por favor, informe o adubo',
  amountIsRequired: 'Por favor, informe a quantidade',
  amountIsInvalid: 'Por favor, informe uma quantidade válida',
  quantityIsRequired: 'Por favor, informe a quantidade',
  quantityIsInvalid: 'Por favor, informe uma quantidade válida',
  pricePerBagIsRequired: 'Por favor, informe o preço por saca',
  deliveryDateIsRequired: 'Por favor, informe a data de entrega',
  nicknameIsRequired: 'Por favor, informe o apelido',
  passwordIsIncorrect: 'Senha incorreta',
  valuePerWeightIsInvalid: 'Por favor, informe um valor por peso válido',
  valuePerWeightIsRequired: 'Por favor, informe o valor por peso',
}

export default validationErrors
