name: Cypress.io
uses: cypress-io/github-action@v5.3.0
run-name: ${{ github.actor }} Is running Cypress.io tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
        env:
          npm_config_cache: '${{ github.workspace }}/.npm'
      - name: Cypress run
        uses: cypress-io/github-action@v5
